# Generated by Django 4.1 on 2022-08-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Portuguese', 'PT'), ('English', 'EN')], max_length=20),
        ),
    ]
